---
- name: Deploy Ubuntu OVA
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    validate_certs: false
    name: "{{ ubuntu_vm_name }}"
    cluster: "{{ vsphere_cluster }}"
    datacenter: "{{ vsphere_datacenter }}"
    datastore: "{{ vsphere_datastore }}"
    resource_pool: "{{ vsphere_resource_pool | default('Resources') }}"
    disk_provisioning: thin
    networks: "{u'VM Network':u'{{ ubuntu_vm_network }}'}"
    ova: "{{ ubuntu_ova_path }}"
    allow_duplicates: false
    power_on: false
    fail_on_spec_warnings: false
    wait: true
    wait_for_ip_address: true
    inject_ovf_env: true
    properties:
      user-data: "{{ lookup('template', 'cloud_init_config.j2') | b64encode }}"
      public-keys: "{{ ubuntu_ssh_public_key | default(omit) }}"
  delegate_to: localhost
  register: vm_instance_data

- name: Get Ubuntu VM UUID
  ansible.builtin.set_fact:
    ubuntu_server_vm_uuid: "{{ vm_instance_data.instance.hw_product_uuid }}"

- name: Configure Ubuntu VM resources
  community.vmware.vmware_guest:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    validate_certs: false
    uuid: "{{ ubuntu_server_vm_uuid }}"
    state: "present"
    hardware:
      memory_mb: "{{ ubuntu_vm_memory }}"
      num_cpus: "{{ ubuntu_vm_cpus }}"
    disk:
      - size_gb: "{{ ubuntu_vm_disk_size }}"
  delegate_to: "localhost"

- name: Power on Ubuntu VM
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    validate_certs: false
    uuid: "{{ ubuntu_server_vm_uuid }}"
    state: powered-on
  delegate_to: localhost

- name: Wait for port 22 to become open and contain "OpenSSH"
  ansible.builtin.wait_for:
    port: 22
    host: "{{ ubuntu_client_ip_address | ansible.utils.ipaddr('address') }}"
    search_regex: OpenSSH
    delay: 10

- name: Add host to an inventory group
  ansible.builtin.add_host:
    name: "{{ ubuntu_client_ip_address | ansible.utils.ipaddr('address') }}"
    groups: "{{ inventory_host_group }}"
    ansible_connection: ssh
    ansible_user: "{{ ubuntu_client_username }}"
    ansible_password: "{{ ubuntu_client_password }}"
