---
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 140
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

ignore: |
  temp/*
  .github/workflows/*
  roles/tanzu/multi-cloud-generate-config/templates/management-cluster.yml
