errand-config:
    smoke-testing:
        post-deploy-state: when-changed
    uaa-deregistration:
        pre-delete-state: false
network-properties:
    network:
        name: infra
    other_availability_zones:
    -   name: az1
    singleton_availability_zone:
        name: az1
product-name: harbor-container-registry
product-properties:
    .harbor-app.static_ips:
        value: 172.29.0.15
    .properties.admin_password:
        value:
            secret: VMware1!
    .properties.admin_password_for_smoketest:
        value:
            secret: VMware1!
    .properties.auth_mode:
        selected_option: db_auth
        value: db_auth
    .properties.customize_container_network:
        selected_option: default
        value: default
    .properties.hostname:
        value: harbor.tkgi.local
    .properties.initial_delay_minutes:
        value: 60
    .properties.log_insight:
        selected_option: disabled
        value: disabled
    .properties.no_proxy:
        value: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair-adapter,chartmuseum,notary-server
    .properties.registry_storage:
        selected_option: filesystem
        value: filesystem
    .properties.server_cert_key:
        value:
            cert_pem: '-----BEGIN CERTIFICATE-----

                MIIFizCCA3OgAwIBAgIUYgtbblTM27La/k7lE6rz3iy2w38wDQYJKoZIhvcNAQEL

                BQAwXDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExCzAJBgNVBAcM

                AkNBMQ8wDQYDVQQKDAZIYXJib3IxGjAYBgNVBAMMEWhhcmJvci50a2dpLmxvY2Fs

                MB4XDTIzMDQxNDEzMTgyOVoXDTMzMDQxMTEzMTgyOVowXDELMAkGA1UEBhMCVVMx

                EzARBgNVBAgMCkNhbGlmb3JuaWExCzAJBgNVBAcMAkNBMQ8wDQYDVQQKDAZIYXJi

                b3IxGjAYBgNVBAMMEWhhcmJvci50a2dpLmxvY2FsMIICIjANBgkqhkiG9w0BAQEF

                AAOCAg8AMIICCgKCAgEAuyqKz5wGuVrOlO1H9IRBpyrHr+joJWwnf1psMLtiPRxa

                0fKltKUoRQclzqhDtfSBscoiVNTzLI0fSTZ5DACwvWZ9LPzipxowAMUESzBq6RrN

                U1UjcUWM2uGWB0lHbhG1NjsXhNiZg7WKBvwshjYtE4MEiLSgTThtzQGZgT6QfxXq

                RyzaqmJ11bw0YtVd5fTMaMHIc0hDzLQJ3dOujkrhPI8et5ou8uBe0x+1pVkjadXE

                EOlsGmNgsl32K3hfmnOy/AVYxk9DUlVDtm0ni24F37a/+frl/EulSzd41xluCNup

                F0ulXIsWWgB5D5ub3We0BxZ82hrpqnlf4cWeCk5lIxqsihQdNnL/YkY50rgwXMqb

                eYl2vROcJ4kbgcI0p0yQFiJQFinq1lOilARpzR7GEF6xDbCa8iXv7kwJvAkDukQy

                eNsrPg3I2OKKleEI0o5gYHhN3TDA6yt5u21lIx0SSZU69N4uhRjaytnA0OZJDp+Z

                eH6BoVljmVMK0Wyy0PIBm3Zo2MJnqpGSZ0nRln+fp+NbpY35KbKKDF20D7hIiugI

                +xso7KWoNVmH4mcFM2jGYYLc0dNmzlNKbEn6EEFTWpgbHsTCuKp5U7GM6tJSrrL5

                Hn1a1pD8Y4c5sMbljpErJqzYatA0zuBXYfcOf3S7lcxvoQrgbs97+PHxjYsYyC0C

                AwEAAaNFMEMwIgYDVR0RBBswGYIRaGFyYm9yLnRrZ2kubG9jYWyHBKwdAA8wHQYD

                VR0OBBYEFNvhty4a3SK+nXjTDxgZTg85HJg/MA0GCSqGSIb3DQEBCwUAA4ICAQAF

                nzVXYCR8Ho5EDYpDVTeDRLLhXpcP+HaR492Mj7yoGuAo35GhkmEa2TrGGrQAd/+u

                M+fHHCIE/jyWnb56KaB00tILLkT+2+vBmhTyUEaLIKc7GbjN0/c1AVSUBblBh2B4

                OzENp+YzpTYaTpDiIBi7QGcz6yAFlG7FUALCHGghDLL28TE9sIXikHale73YvnyK

                bwCdJ5QhFy7UJLRXQve72NMBNNFpvmE7mmd7NaZEvhMsQN49OKxZAjdwbEhezgvI

                oXtubs+GanAbTwnkAtZYXKgD+YYGtivktDREKa2juPr8j4pbzZZOHNKblOgdBt63

                YXMS3OOqH0nxpuHfXKJksIV4n7jX0fl3lkkIZvwmYQ2GnGcf4As7JEkh21v9hWqH

                eqfMdMhkdHaP/AEYiCN8V7gWB/jTNenSj8kc5LKidVfTvjtI0r4HnSk2VcT1IwJ2

                D7rVjBd2XRYv5OptNLFbZQnM4+EcTnnizAxMVeiWLBW3hny+AQ8knDgOUWdsPtFl

                WI87GQT3kPN9YHeE6gFGWOPApzsPQy1HR3WCQ8ew1a13pfNWtOy2/QLfijDvri7z

                HqjjEZcEUmHZ8XGX/AnRUWwVQ+pDRIzoOdNwzX2kSCda8xMKareaWZb0CbAKbG6K

                lydUGQovAUSPraVf/7DVwieFMQqBmzq61dXJW+m8UA==

                -----END CERTIFICATE-----'
            private_key_pem: '-----BEGIN RSA PRIVATE KEY-----

                MIIJKAIBAAKCAgEAuyqKz5wGuVrOlO1H9IRBpyrHr+joJWwnf1psMLtiPRxa0fKl

                tKUoRQclzqhDtfSBscoiVNTzLI0fSTZ5DACwvWZ9LPzipxowAMUESzBq6RrNU1Uj

                cUWM2uGWB0lHbhG1NjsXhNiZg7WKBvwshjYtE4MEiLSgTThtzQGZgT6QfxXqRyza

                qmJ11bw0YtVd5fTMaMHIc0hDzLQJ3dOujkrhPI8et5ou8uBe0x+1pVkjadXEEOls

                GmNgsl32K3hfmnOy/AVYxk9DUlVDtm0ni24F37a/+frl/EulSzd41xluCNupF0ul

                XIsWWgB5D5ub3We0BxZ82hrpqnlf4cWeCk5lIxqsihQdNnL/YkY50rgwXMqbeYl2

                vROcJ4kbgcI0p0yQFiJQFinq1lOilARpzR7GEF6xDbCa8iXv7kwJvAkDukQyeNsr

                Pg3I2OKKleEI0o5gYHhN3TDA6yt5u21lIx0SSZU69N4uhRjaytnA0OZJDp+ZeH6B

                oVljmVMK0Wyy0PIBm3Zo2MJnqpGSZ0nRln+fp+NbpY35KbKKDF20D7hIiugI+xso

                7KWoNVmH4mcFM2jGYYLc0dNmzlNKbEn6EEFTWpgbHsTCuKp5U7GM6tJSrrL5Hn1a

                1pD8Y4c5sMbljpErJqzYatA0zuBXYfcOf3S7lcxvoQrgbs97+PHxjYsYyC0CAwEA

                AQKCAgAzbcUmtuDCHcmV8n1LGuxPWtnz5DOl1MolnFsOKO8di6UI+3u834TpMsWY

                u3Ofk8fvanN0i+8l1sE6BNXODoKCCJ9stTAyame2TmyXnH5D/zFcLJDIlyvVGRd4

                eRI/lG4OsL4NqtbD8iYzNSem2UwZiG6+gaNqlI7XPhFICkD6KrNtS03qc5OdX1Gl

                tqtOfK2OO3Ew/DJlFTOA2KGmR70MPudZ2+v6oNxtdtEa1ht9AVgWrY0e0x/G4zq5

                RyI99ny/81gpZa5B+VvZzLSJA3pptnWZ4u8/HCoXOO7jbAFoPbOAyzBs9Wr24Bpj

                x4ZUmCJHsE4uQCbkyOUnzH1Yp6HyQo6ounRsN8aaPG+Qsb9giNF6H0DJOtkFNDjJ

                5IXFHJxTJPeGXXXmsalPwiUUITtxAUimSKy+BWltYJuUWmuDO0lsppl7vMswS6RH

                2yAnQcIPR24lfmDT9sASUeVcCmviteGf26wogAfVK7k0XNKcx3tm7nAnszeN6Z4W

                LsNOtLjtzi4OTL5+fiQ7y/0llL2yLpY44+6ReubftfL2r+lua+vjUQgIiMeblUbI

                XSmnQcfurltXcnpn2otaNOHPx5SyXq7PnbrOQXFBtsecUKUcfDeqt5HbdbSe7tyH

                dxOg6Jay4nUA8siQcee4sAPOL20PMlynPa7+959WiQGAvLUroQKCAQEA8Rf51B+p

                lMoqtI8USbmp4InoJA00vhHRFlkbX1SBWzEiT6cYCTA+bgTSk4chOWZGjVLvRfz1

                2bq9YvfAlDGn5Nf9Y4lWk/jgLbYsoI2oXdoaJuJ9EcYF/ybBYCWmI3Nw/Itoues9

                LNg90BhxeOPne8hPWgtKU7U5apz0rtenLifDTT8KJcZ5AOemEC6WWMBMwuSHFOt5

                0714M7i33+ulu30CzcaTy9v5Chuyca48Scko/vg9BchuaqPwOaJE3LxDmWbZkCaf

                c0rwI7XAKQeNiHbdGGW40VymMEB3ebV6IOVgKYl1o6LIsbwFDcFsn7aCKOW7ywf2

                S6ZolOvW4w4VMwKCAQEAxr0A8BSn4Bnk2JtudmxuVYMjwLGg9hdb1Sl2r/zIxDNl

                /JZoZFX/2Y+iHejWVxuFLFNvQfk2m/A7kmWAUXQNf9Aw3KYUMfO5JkOzS/epiXDD

                9ygXueaBNoCQ8JfiMge+TOG7t9Lb72rDzb8d8s/OZyQXJbnrnaGfAoeRRYLyYSQS

                g/n6W2VTuymIeNsLuaXTRo7lPMklcYCSY7ecCmazDtTEJTDafP6OArygQ8hm+tXd

                VI25kW48IMk3td9nomToi9Ko4TaY3u+RC2BkNCJXn1yDXfSBJwA6Y+Ojsu4BKKFG

                x+M1qRSJgHz1/e+Aa1I0Dy8BMW1jJ2Xo87XaKiztHwKCAQEAzKQZPuCRROZFUXWR

                NvMNKrZkARXkiuD8pQeFoGlOU2VlRk8Cq+nzU9dsFiVBIkOZ5yNaTgHlfKZxUqwR

                Hrj3VduwDOjqQDejsalMQAt9ugwC3raoiomXVXhD86SBXN4ELZj3j7gI+SOjdBsL

                Vh28wujH0hp7QIo27jPDzRTnptnBgLPdnSrWUtpNrracj0DK5zKrJiqqAfx1JxHH

                oZ2X04jM9HV1xjg1L0tLMAtAyTCiR6nVwi7a6lG0+nauFN8IUhFm4mCmP2qAYw9G

                yIzMqeSazrapJayKs7JEt14/B+Uqtpci736g85wwffiMhxSXbrdxq2hauuPJKX71

                q0ys2QKCAQAbbCr79a2wY4JLTS8x0gZrcDv3s8rlChYW1LDW2ceOIxV4g/yFk8RI

                7ePNwroIrPh0RFL+xHd/jud5bN4G3z+Zmk2TtKrmtZ2fpQnReqv/FftEWFjlwuOj

                dJwLRrnkc2MT0rYHSGYmpBG+ixeD0J7HZph3ES9swcdiHvixob72HncblNuxzsp9

                8d4t5vO4OyRrAP6qo4qyHa6VadlzKfadHkiuZQ5Q3wMTZ5mpoLZs+COhLikj4xUS

                5RD13Iy9QLVBzeCVquXvJRlbe4J4GyECEU7jIQDNM9/atqd44hRw2cgdfsGBwh6z

                BwsebfTHWkFqsu60NkbPQeWh8z7WQPq7AoIBAF6n53fFvaKev6MHl9zFxxPKpOhw

                zRnEtNpe4d6NnDA+Pu4UPizP1ZCBUuFfnXYn+uzZvPe99tkBV3xyok7cu8kq49U0

                wzCv/8BdpSCRlIFGDJ3xTzz6nAix1Hz5/LP72NNTj2Am/H8yaHaZphNJhqLa3Vg+

                l8KCZ45f6nPcgdqpRr/a9ziWA9QoT/Zemqj4vxPnrZs54bnK8nLVcg7ag7ASAjuC

                s2twmG8CwypTjRXChAeEkgY826K9spgvg3Pt5GdP90tC0w6Z9hedn6SjfX+NDosW

                30dJlQ7Nf/2Wg/2iqaEReg3fyXeGhyk5b4LnBf9RjDqybSEZiqeDErLWI18=

                -----END RSA PRIVATE KEY-----'
    .properties.trivy_offline_scan:
        value: true
    .properties.trivy_skip_update:
        value: false
    .properties.vm_monitor:
        selected_option: no_monitor
        value: no_monitor
    .properties.with_notary:
        value: true
    .properties.with_trivy:
        value: true
resource-config:
    harbor-app:
        additional_networks: []
        additional_vm_extensions: []
        instance_type:
            id: automatic
        instances: automatic
        max_in_flight: 1
        nsx:
            lbs: []
            security_groups: []
        nsxt:
            lb:
                server_pools: []
            ns_groups: []
            vif_type: null
        persistent_disk:
            name: automatic
            size_mb: automatic
        swap_as_percent_of_memory_size: automatic
    smoke-testing:
        additional_networks: []
        additional_vm_extensions: []
        instance_type:
            id: automatic
        instances: automatic
        max_in_flight: 1
        nsx:
            lbs: []
            security_groups: []
        nsxt:
            lb:
                server_pools: []
            ns_groups: []
            vif_type: null
        swap_as_percent_of_memory_size: automatic
