---
- name: Debugging
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get a cert from an https port
      community.crypto.get_certificate:
        host: "www.google.com"
        port: 443
      delegate_to: localhost
      run_once: true
      register: cert
    
    - debug: var=cert