---
opsman-configuration:
  vsphere:
    vcenter:
      # ca_cert: cert                 # REQUIRED if insecure = 0 (secure)
      datacenter: "{{ opsman_vcenter_datacenter }}"
      datastore: "{{ opsman_vcenter_datastore }}"
      folder: "{{ opsman_vcenter_folder }}" # RECOMMENDED, but not required
      url: "{{ opsman_vcenter_url }}"
      username: "{{ opsman_vcenter_username }}"
      password: "{{ opsman_vcenter_password }}"
      resource_pool: "{{ opsman_vcenter_resource_pool }}"
      # resource_pool can use a cluster - /example-dc/host/example-cluster
      insecure: 1     # default - 0 (secure) | 1 (insecure)

    disk_type: thin     # thin|thick
    dns: "{{ opsman_dns }}"
    gateway: "{{ opsman_gateway }}"
    hostname: "{{ opsman_hostname }}"
    netmask: "{{ opsman_netmask }}"
    network: "{{ opsman_network }}"
    ntp: "{{ opsman_ntp }}"
    private_ip: "{{ opsman_ip }}"
    ssh_public_key: "{{ opsman_ssh_public_key }}"   # REQUIRED Ops Manager >= 2.6
    vm_name: "{{ opsman_vm_name }}"

    # Optional
    # cpu: 1                         # default - 1
    # memory: 8                      # default - 8 (GB)
    # disk_size: 200                 # default - 160 (GB), only larger values allowed

  # Optional Ops Manager UI Settings for upgrade-opsman
  # ssl-certificate: ...
  # pivotal-network-settings: ...
  # banner-settings: ...
  # syslog-settings: ...
  # rbac-settings: ...