---
- debug: msg="{{ nsxt.vlan_segments }}"

- name: Create VLAN segments
  vmware.ansible_for_nsxt.nsxt_policy_segment:
    hostname: "{{ nsxt.manager.hostname }}"
    username: "{{ nsxt.manager.username }}"
    password: "{{ nsxt.manager.password }}"
    validate_certs: false
    display_name: "{{ item.display_name }}"
    state: present
    transport_zone_display_name: "{{ item.transport_zone_display_name }}"
    vlan_ids: "{{ item.vlan_ids }}"
    tags: "{{ item.tags | default(omit) }}"
    do_wait_till_create: true
  loop: "{{ nsxt.vlan_segments }}"
  register: vlan_segment_results
  retries: 36
  delay: 5
  until: vlan_segment_results is success
