---
- name: Create dummy Pool to force SE creation
  avi_pool:
    avi_credentials: "{{ avi_credentials }}"
    name: dummy-pool
    state: present

- name: Create vsvip for virtualservice for newtestvs
  avi_vsvip:
    avi_credentials: "{{ avi_credentials }}"
    name: vsvip-dummy
    cloud_ref: /api/cloud/?name=Default-Cloud
    vip:
      - vip_id: '1'
        auto_allocate_ip_type: V4_ONLY
        auto_allocate_ip: true
        ipam_network_subnet:
          network_ref: "/api/network?name={{ dummy_service_network_name }}"
          subnet:
            ip_addr:
              addr: "{{ dummy_service_subnet_addr }}"
              type: "V4"
            mask: "{{ dummy_service_subnet_mask }}"

- name: Create dummy Virtual Service to force SE creation
  avi_virtualservice:
    avi_credentials: "{{ avi_credentials }}"
    name: dummy-vip
    state: present
    services:
      - port: 80
    application_profile_ref: '/api/applicationprofile?name=System-L4-Application'
    type: VS_TYPE_NORMAL
    cloud_ref: "/api/cloud?name=Default-Cloud"
    pool_ref: '/api/pool?name=dummy-pool'
    vsvip_ref: /api/vsvip/?name=vsvip-dummy

- name: Pause for 10 seconds ensure SE is created
  pause:
    seconds: 10

- name: Delete dummy Virtual Service to force SE creation
  avi_virtualservice:
    avi_credentials: "{{ avi_credentials }}"
    name: dummy-vip
    state: absent

- name: Delete vsvip for virtualservice for newtestvs
  avi_vsvip:
    avi_credentials: "{{ avi_credentials }}"
    name: vsvip-dummy
    state: absent

- name: Delete dummy Pool to force SE creation
  avi_pool:
    avi_credentials: "{{ avi_credentials }}"
    name: dummy-pool
    state: absent
