---
- name: Create transport zone
  vmware.ansible_for_nsxt.nsxt_transport_zones:
    hostname: "{{ nsxt.manager.hostname }}"
    username: "{{ nsxt.manager.username }}"
    password: "{{ nsxt.manager.password }}"
    validate_certs: false
    state: "present"
    display_name: "{{ item.display_name }}"
    description: "{{ item.description }}"
    host_switch_name: "{{ item.host_switch_name | default(omit) }}"
    nested_nsx: "{{ item.nested_nsx | default(omit) }}"
    resource_type: "TransportZone"
    tags: "{{ item.tags | default(omit) }}"
    transport_type: "{{ item.transport_type }}"
  loop: "{{ nsxt.transport_zones }}"
  register: tz_results

- name: Waiting 20 seconds for transport zone to configured
  pause:
    echo: false
    seconds: 20
  when: tz_results.changed
