---
# Build a list of resource pools to add and ignore cluster if none specified
- name: Build resource pools to add
  ansible.builtin.set_fact:
    resource_pools_to_add: >-
      [
        {% for cluster_name, cluster_spec in nested_clusters.items() %}
        {% if "resource_pools" in cluster_spec %}
        {% for resource_pool in cluster_spec.resource_pools %}
        {
          "cluster_name": "{{ cluster_name }}",
          "resource_pool": "{{ resource_pool }}",
        },
        {% endfor %}
        {% endif %}
        {% endfor %}
      ]

- name: Add resource pools to vCenter
  ansible.builtin.include_role:
    name: vsphere/vsphere-resource-pool
  vars:
    vcenter_ip: "{{ nested_vcenter.ip }}"
    vcenter_username: "{{ nested_vcenter.username }}"
    vcenter_password: "{{ nested_vcenter.password }}"
    datacenter: "{{ nested_vcenter.datacenter }}"
    cluster_name: "{{ item.cluster_name }}"
    resource_pool: "{{ item.resource_pool }}"
  loop: "{{ resource_pools_to_add }}"
