---

- name: Fetch NSX Manager cert
  ansible.builtin.shell: |
    openssl s_client -showcerts -servername {{ tkgi_nsx_manager_url }} \
      -connect {{ tkgi_nsx_manager_url }}:443 </dev/null \
      | openssl x509 -outform pem
  register: result_nsx_manager_cert_pem
  changed_when: false

- name: Set NSX CA Cert
  ansible.builtin.set_fact:
    nsx_ca_cert: |-
      {{ result_nsx_manager_cert_pem.stdout }}

- name: NSX Manager cert check
  ansible.builtin.shell: |
    openssl s_client -showcerts -servername 192.168.1.11 -connect 192.168.1.11:443 </dev/null | \
      sed -n -e '/BEGIN\ CERTIFICATE/,/END\ CERTIFICATE/ p'
  register: result_nsx_manager_cert
  changed_when: false


- name: Setting TKGi Tile vars
  set_fact:
    nsx_manager_cert: "{{ result_nsx_manager_cert.stdout }}"

- name: Setting TKGi Tile vars
  set_fact:
    tkgi_vars:
      - slug: pivotal-container-service
        file_path: "{{ tkgi_tile }}"
        product_config: "{{ lookup('template', 'tkgi.yml') | from_yaml }}"

- name: Deploy TKGi
  ansible.builtin.include_role:
    name: tanzu/opsman/upload-stage-configure-tile
  with_items: "{{ tkgi_vars }}"